name: "Copilot Setup Steps"

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_LENGTH_1_CONDITION_: TRUE #deprecated from R 4.2.0
      _R_CHECK_MATRIX_DATA_: TRUE       # only works from R 4.2.0 onwards

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies on linux
        run: |
          # ragg                                          requires libharfbuzz-dev libfribidi-dev 
          # credentials   (dependency of usethis)         requires libgit2-dev
          # curl          (dependency of usethis)         requires libcurl4-openssl-dev
          # libicu   (dependency of igraph or stringi...) requires libicu libicu-dev

          sudo apt install libharfbuzz-dev libfribidi-dev libgit2-dev libcurl4-openssl-dev libicu*
        shell: bash
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            local::.
            github::vandenman/jaspTools@llm
          needs: check
          cache-version: 3

      - name: Setup jaspTools
        run: |
          jaspTools::setupJaspTools(pathJaspDesktop = NULL, installJaspModules = FALSE, installJaspCorePkgs = FALSE, quiet = TRUE, force = TRUE)
        shell: Rscript {0}

      - name: Run unit tests
        run: source("tests/testthat.R")
        shell: Rscript {0}
